# Welcome to Jekyll!
title: Online Resume
url:
baseurl: ""

# Sass setting
sass/style: compressed

# Privacy
open: true                  # show or hide your resume
allow_search_engines: false  # allow your resume indexing by search engine, 'true' or 'false'
description:                # your resume description
open_graph:
  enable: false                        # enable open graph meta tags
  image: /assets/images/profile.jpg   # path or link to the open graph image

# Style
date_format: "%Y-%m-%d"     # date format
theme_color: "#1DA1F2"      # your favorite theme color
contact_delimiter: "·"      # contact delimiter, '·', '/' or '|'
section_icon: true          # section title icon, true or false
section_title: uppercase    # section title style, 'uppercase', 'lowercase', 'capitalize' or 'none'
section_align: start        # section title align, 'start', 'end' or 'center'
section_line: dashed        # section title line, 'solid', 'dashed' or 'none'
section_background: false   # section title backound, 'true' or 'false'
skill_level_icon: lightbulb # skill rate icon, 'heart', 'star', 'circle' or 'lightbulb'
link_icon: true             # show link icon, 'true' or 'false'
site_footer: true           # show site footer, 'true' or 'false'

# Analytics
analytics:
  google:                   # google
  cloudflare:               # cloudflare
  umami:                    # umami (Replace it with your own)
    script: https://cloud.umami.is/script.js
    website_id: 36e6500f-b787-47c2-905d-d2a8544d1b34
    domains: boldyrev.me
