title: Online Resume
baseURL: ""
languageCode: en
defaultContentLanguage: en

# Privacy
params:
  open: true
  allow_search_engines: false
  description: ""
  open_graph:
    enable: false
    image: /assets/images/profile.jpg

  # Style
  date_format: "2006-01-02"
  theme_color: "#1DA1F2"
  contact_delimiter: "Â·"
  section_icon: true
  section_title: uppercase
  section_align: start
  section_line: dashed
  section_background: false
  skill_level_icon: lightbulb
  link_icon: true
  site_footer: true

  # Analytics
  analytics:
    google: ""
    cloudflare: ""
    umami:
      script: /um/um.js
      website_id: 0f6684c1-2c0a-4d23-8dbe-3a432c3b9ddc
      host_url: /um
      domains: pavel.boldyrev.me

# Build settings
build:
  writeStats: false

# Markup
markup:
  goldmark:
    renderer:
      unsafe: false
  highlight:
    style: github
    codeFences: true

# Output formats
outputs:
  home:
    - HTML
    - RSS
